<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Category extends Model
{
    /** @use HasFactory<\Database\Factories\CategoryFactory> */
    use HasFactory;

    protected $fillable = ['name'];

    function products(){
        return $this->hasMany(Product::class);
    }

    public function call($scope, array $parameters = [])
    {
        return parent::callNamedScope($scope, $parameters); // TODO: Change the autogenerated stub
    }
    public function rules(): array{
        return [
            'name' => 'required'
        ];
    }
}
